"""Lightweight AI-attribution heuristics for PR and commit metadata."""

from __future__ import annotations

from dataclasses import dataclass


AI_PATTERNS: tuple[tuple[str, str], ...] = (
    ("github copilot", "Copilot"),
    ("copilot", "Copilot"),
    ("cursor", "Cursor"),
    ("claude", "Claude"),
    ("chatgpt", "ChatGPT"),
    ("openai", "OpenAI"),
    ("anthropic", "Anthropic"),
    ("ai-assisted", "AI-assisted"),
    ("ai generated", "AI-generated"),
    ("generated by ai", "AI-generated"),
    ("generated with ai", "AI-generated"),
)


@dataclass(frozen=True)
class CommitMetadata:
    """Subset of commit metadata relevant to lightweight attribution."""

    message: str = ""
    author_name: str = ""
    author_email: str = ""
    co_authors: tuple[str, ...] = ()


@dataclass(frozen=True)
class PullRequestMetadata:
    """Subset of PR metadata consumed by attribution heuristics."""

    title: str = ""
    body: str = ""
    labels: tuple[str, ...] = ()
    commits: tuple[CommitMetadata, ...] = ()


@dataclass(frozen=True)
class AiAttribution:
    """Explainable AI-origin signals detected from PR metadata."""

    detected: bool
    signal_count: int
    ai_authored_commits: int
    sources: tuple[str, ...]
    indicators: tuple[str, ...]


def parse_pull_request_metadata(payload: dict[str, object]) -> PullRequestMetadata:
    """Parse a permissive PR metadata JSON payload into a stable model."""

    raw_commits = payload.get("commits")
    commits: list[CommitMetadata] = []

    if isinstance(raw_commits, list):
        for raw_commit in raw_commits:
            if not isinstance(raw_commit, dict):
                continue
            commits.append(
                CommitMetadata(
                    message=_as_string(raw_commit.get("message")),
                    author_name=_as_string(raw_commit.get("author_name")),
                    author_email=_as_string(raw_commit.get("author_email")),
                    co_authors=_as_string_tuple(raw_commit.get("co_authors")),
                )
            )

    return PullRequestMetadata(
        title=_as_string(payload.get("title")),
        body=_as_string(payload.get("body")),
        labels=_as_string_tuple(payload.get("labels")),
        commits=tuple(commits),
    )


def detect_ai_attribution(metadata: PullRequestMetadata | None) -> AiAttribution:
    """Detect lightweight AI-origin signals from PR and commit metadata."""

    if metadata is None:
        return AiAttribution(
            detected=False,
            signal_count=0,
            ai_authored_commits=0,
            sources=(),
            indicators=(),
        )

    sources: set[str] = set()
    indicators: set[str] = set()
    ai_authored_commits = 0

    if _match_indicators(metadata.title):
        sources.add("pr_title")
        indicators.update(_match_indicators(metadata.title))
    if _match_indicators(metadata.body):
        sources.add("pr_body")
        indicators.update(_match_indicators(metadata.body))
    for label in metadata.labels:
        label_hits = _match_indicators(label)
        if label_hits:
            sources.add("pr_label")
            indicators.update(label_hits)

    for commit in metadata.commits:
        commit_detected = False

        message_hits = _match_indicators(commit.message)
        if message_hits:
            sources.add("commit_message")
            indicators.update(message_hits)
            commit_detected = True

        author_hits = _match_indicators(" ".join((commit.author_name, commit.author_email)))
        if author_hits:
            sources.add("commit_author")
            indicators.update(author_hits)
            commit_detected = True

        for co_author in commit.co_authors:
            co_author_hits = _match_indicators(co_author)
            if not co_author_hits:
                continue
            sources.add("commit_co_author")
            indicators.update(co_author_hits)
            commit_detected = True

        if commit_detected:
            ai_authored_commits += 1

    return AiAttribution(
        detected=bool(sources),
        signal_count=len(sources),
        ai_authored_commits=ai_authored_commits,
        sources=tuple(sorted(sources)),
        indicators=tuple(sorted(indicators)),
    )


def _match_indicators(text: str) -> tuple[str, ...]:
    if not text:
        return ()

    normalized = text.casefold()
    matches = [label for pattern, label in AI_PATTERNS if pattern in normalized]
    return tuple(dict.fromkeys(matches))


def _as_string(value: object) -> str:
    return value.strip() if isinstance(value, str) else ""


def _as_string_tuple(value: object) -> tuple[str, ...]:
    if not isinstance(value, list):
        return ()
    return tuple(item.strip() for item in value if isinstance(item, str) and item.strip())
